### ISSUE TITLE
Issue with statamic blueprint

### ISSUE THREAD

**Issue by sandcatit-owner** [justbetter/statamic-translation-manager#5]
I installed your addon and have issue with fieldtypes.

When visiting the translations page on Statamic I got error `StatamicRadPack\Runway\Http\Controllers\CP\ResourceController::getPrimaryColumn(): Return value must be of type string, null returned` the path is `cp/runway/language_line`

When I change `resources/blueprints/vendor/runway/language_line.yaml` file to default fields, the index page works.
```
tabs:
  main:
    fields:
      -
        handle: group
        field:
          type: text
          display: Group
          validate: required
      -
        handle: key
        field:
          type: text
          display: Key
          validate: required
  sidebar:
    fields: {  }
```

 I'm guessing issue is in fieldtypes or field registration, maybe something desn't render on index page, could you help me solve this?

Statamic version: 5.45
PHP version: 8.3
